export const pakistaniCities = [
  "Ahmed Nager Chatha",
  "Ahmadpur East",
  "Ali Khan Abad",
  "Attock",
  "Bahawalnagar",
  "Bahawalpur",
  "Bhakkar",
  "Burewala",
  "Chakwal",
  "Chichawatni",
  "Dera Ghazi Khan",
  "Faisalabad",
  "Gujranwala",
  "Gujrat",
  "Hafizabad",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jhang",
  "Jhelum",
  "Kasur",
  "Khanewal",
  "Karachi",
  "Khushab",
  "Lahore",
  "Larkana",
  "Mandi Bahauddin",
  "Mianwali",
  "Multan",
  "Muzaffargarh",
  "Nankana Sahib",
  "Narowal",
  "Okara",
  "Peshawar",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sahiwal",
  "Sargodha",
  "Sheikhupura",
  "Sialkot",
  "Sukkur",
  "Vehari",
  "Wah Cantonment",
  "Wazirabad"
];
