import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  fullContainer: { flex: 1 },
  scroll: { padding: 20, paddingBottom: 100 },
  heading: { fontSize: 24, fontWeight: "700", marginBottom: 20 },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 10,
  },
  label: { fontSize: 16, fontWeight: "600", marginBottom: 6, marginTop: 12 },
  inputGroup: { marginBottom: 15 },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 8,
    marginVertical: 10,
  },
  uploadedImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  navigationContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
    borderTopWidth: 1,
  },
  navigationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  navButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  draftButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  navButtonText: { color: "#fff", fontWeight: "600", fontSize: 16 },
  stepNavContainer: { flexDirection: "row", alignItems: "center" },
  amenityTile: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginVertical: 4,
    marginRight: 8,
    width: "48%",
    justifyContent: "center",
  },
  amenityText: { marginLeft: 10, fontWeight: "500", textAlign: "center" },
});
